### ISSUE TITLE
[Không liên quan lắm] SSL certificate của web bạn bị lỗi

### ISSUE THREAD

**Issue by tuankiet65** [natsukagami/themis-web-interface-rpc#1]
Căn bản là https://blog.nkagami.me mình vào không được vì CloudFlare bảo SSL ở origin aka server của bạn không hợp lệ. Mình thấy ở https://twi.nkagami.me thì:
* bạn dùng Let's Encrypt, cơ mà Let's Encrypt thì hạn dùng certificate chỉ có 90 ngày, sau đó phải renew. Cái này thì bạn nên set up cron hoặc một cái gì đó để nó tự động renew certificate giúp cho bạn.
* có vẻ là bạn đang dùng nhiều certificate khác nhau cho nhiều subdomain khác nhau. Let's Encrypt bữa nay cho bạn đăng kí một certificate áp dụng cho nhiều (sub)domain, và hơn nữa là cho wildcard domain, cho nên bạn chỉ cần tạo một certificate bao gồm domain `nkagami.me` và `*.nkagami.me` là được. Như vậy vừa tiện vừa cho phép sau này bạn muốn tạo bao nhiêu subdomain cũng được mà chỉ cần dùng 1 certificate duy nhất.

Cảm ơn ban đã đọc tới đây :v

**Comment by natsukagami** [comment]
- Cho điểm thứ nhất của bạn: Mình **đang** dùng bot renew cert cho twi.nkagami.me, mình chỉ không vứt config của nó ở đây thôi (ai lại thế chứ?)
- Cũng chính vì việc này nên nó dẫn đến điểm thứ hai: mình *không* dùng dịch vụ hosting gì để chạy blog.nkagami.me (mình dùng static hosting của Github Pages) vì thế nên có muốn share cert cũng không được :)) chắc do mình cấu hình CloudFlare bị ngu nên blog.nkagami.me không vào được nữa

**Comment by tuankiet65** [comment]
Point 2: vậy chắc là bạn để SSL mode là `Full (strict)` chứ không phải là `Full` :v ([trong hướng dẫn của CloudFlare nó nói vậy](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/))

**Comment by natsukagami** [comment]
Nope, mình cố tình để Strict.

Mình để record theo kiểu cũ của GitHub Pages (record A thay vì CNAME) nên nó không dùng được nữa thôi :)) Fixed
